-- Primer query
 
SELECT 
	YEAR(V.FECHA_VENTA) AS ANIO,
	MONTH(V.FECHA_VENTA) AS MES,
	M.NOMBRE_MONEDA AS MONEDA,
	SUM(P.CANTIDAD) AS TOTAL
FROM VENTAS AS V
INNER JOIN CLIENTES AS C ON V.CLIENTE_ID = C.CLIENTE_ID
INNER JOIN PAGO AS P ON V.VENTA_ID = P.VENTA_ID
INNER JOIN TIPO_MONEDA AS M ON P.TIPO_MONEDA_ID = M.ID
WHERE C.NIT_CLIENTE = '010120' AND 
	  C.ESTADO_VENTA = 'CANCELADO'
GROUP BY YEAR(V.FECHA_VENTA), MONTH(V.FECHA_VENTA), M.NOMBRE_MONEDA
ORDER BY ANIO, MES, M.NOMBRE_MONEDA

-- Segundo query

SELECT ANIO, PRODUCTO, CANTIDAD
FROM(
	SELECT
		YEAR(V.FECHA_VENTA) AS ANIO,
		P.NOMBRE_PRODUCTO AS PRODUCTO,
		SUM(DV.CANTIDAD_VENTA) AS CANTIDAD,
		RANK() OVER(PARTITION BY YEAR(V.FECHA_VENTA), P.NOMBRE_PRODUCTO ORDER BY SUM(DV.CANTIDAD_VENTA) DESC) AS TP
	FROM 
	VENTA AS V
	INNER JOIN DETALLE_VENTA AS DV ON V.ID = DV.VENTA_ID
	INNER JOIN INVENTARIO AS I ON DV.INVENTARIO_ID = I.ID
	INNER JOIN PRODUCTO AS P ON I.PRODUCTO_ID = P.ID
	WHERE 
		P.ESTADO_PRODUCTO = 'ACTIVO' AND
		I.ESTADO_INVENTARIO = 'ACTIVO' AND
		DV.ESTADO_DETALLE = 'ACTIVO' AND
		V.ESTADO_VENTA = 'CANCELADO'
	GROUP BY YEAR(V.FECHA_VENTA), P.NOMBRE_PRODUCTO
)
WHERE TP = 1;

